services:
  ord-indexer:
    image: verydogelabs/wonky-ord-dogecoin
    env_file:
      - .env
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - STARTING_SATS_PATH=/starting_sats.json
      - SUBSIDIES_PATH=/subsidies.json
      - FIRST_INSCRIPTION_HEIGHT=4609723
      - FIRST_DUNE_HEIGHT=5084000
    tty: false
    restart: "always"
    # for the indexer to be able to connect to the local dogecoin node we use the host network
    network_mode: "host"
    #    ports:
    #      - ${ORD_HTTP_PORT:-8080}:80
    entrypoint: [
      "ord",
      "--rpc-url=${RPC_URL:-127.0.0.1:22555}",
      "--cookie-file=${DOGE_COOKIE_FILE_CONTAINER:-/root/.dogecoin/.cookie}",
      "--data-dir=/root/.data",
      "--nr-parallel-requests=${NR_PARALLEL_REQUESTS:-16}",
      "--first-inscription-height=${FIRST_INSCRIPTION_HEIGHT}",
      "--first-dune-height=${FIRST_DUNE_HEIGHT}",
      "--index-dunes",
      "--index-transactions",
      "--index-drc20",
      "server",
      "--http-port=${ORD_HTTP_PORT}"
    ]
    volumes:
      - ${DOG_MOUNT_DIR_INDEXER:-/mnt/storage1/dogecoin/ord-node}/indexer-data-main:/root/.data:delegated
      - ${DOGE_COOKIE_FILE_HOST}:${DOGE_COOKIE_FILE_CONTAINER:-/root/.dogecoin/.cookie}:ro
      # If your dogecoin node is running in a container, you can mount the dogecoin data directory to the indexer container
      # - dog-data:/root/.dogecoin
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    privileged: true
